export const LIMITS = {
  MAX_TICKETS_PER_CPF: 4,
  ORDER_EXPIRY_PIX_MS: 15 * 60 * 1000,
  ORDER_EXPIRY_CARD_MS: 10 * 60 * 1000,
  ORDER_EXPIRY_BOLETO_MS: 3 * 24 * 60 * 60 * 1000,
  TOTP_WINDOW: 1,
  TOTP_STEP: 30,
  MAX_TRANSFER_COUNT: 3,
  FLASH_SALE_QUEUE_TTL: 300,
  PAGINATION_DEFAULT_LIMIT: 20,
  PAGINATION_MAX_LIMIT: 100,
} as const;

export const API_LIMITS = {
  MAX_FILE_SIZE_MB: 10,
  MAX_IMAGE_SIZE_MB: 5,
  MAX_BULK_OPERATIONS: 100,
  MAX_BATCH_ITEMS: 50,
} as const;

export const TIME_LIMITS = {
  EVENT_DESCRIPTION_MAX_CHARS: 5000,
  REVIEW_MAX_CHARS: 500,
  COMMENT_MAX_CHARS: 1000,
  BIO_MAX_CHARS: 500,
} as const;
